src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface; 

#[ORM\Entity(repositoryClass: ContratRepository::class)]
class Contrat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

#[ORM\ManyToOne(inversedBy: 'contrats')]
#[ORM\JoinColumn(nullable: false)]
private ?User $employe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 700)]

    
    private ?string $signaturePath = null;

    #[ORM\ManyToOne]
    private ?Centre $centre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

   

   
public function getEmploye(): ?User
{
    return $this->employe;
}

public function setEmploye(?User $employe): static
{
    $this->employe = $employe;

    return $this;
}

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getSignaturePath(): ?string
    {
        return $this->signaturePath;
    }

    public function setSignaturePath(string $signaturePath): static
    {
        $this->signaturePath = $signaturePath;

        return $this;
    }

    public function getCentre(): ?Centre
    {
        return $this->centre;
    }

    public function setCentre(?Centre $centre): static
    {
        $this->centre = $centre;

        return $this;
    }
    #[Assert\Callback]
    public function validateDates(ExecutionContextInterface $context): void
    {
        if ($this->date_debut !== null && $this->date_fin !== null) {
            if ($this->date_fin <= $this->date_debut) {
                $context->buildViolation('La date de fin doit être postérieure à la date de début.')
                    ->atPath('date_fin')
                    ->addViolation();
            }
        }
    }   
}

src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TacheRepository::class)]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Le centre est requis")]
    #[Assert\Positive(message: "L'ID du centre doit être positif")]
    private ?int $id_centre = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "L'employé est requis")]
    #[Assert\Positive(message: "L'ID de l'employé doit être positif")]
    private ?int $id_employe = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank(message: "L'altitude est requise")]
    #[Assert\Range(
        min: -1000,
        max: 10000,
        notInRangeMessage: "L'altitude doit être entre {{ min }} et {{ max }} mètres"
    )]
    private ?float $altitude = null;

    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank(message: "La longitude est requise")]
    #[Assert\Range(
        min: -180,
        max: 180,
        notInRangeMessage: "La longitude doit être entre {{ min }} et {{ max }} degrés"
    )]
    private ?float $longitude = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le message est requis")]
    #[Assert\Length(
        max: 255,
        maxMessage: "Le message ne peut pas dépasser {{ limit }} caractères"
    )]
    private ?string $message = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "L'état est requis")]
    #[Assert\Length(
        max: 255,
        maxMessage: "L'état ne peut pas dépasser {{ limit }} caractères"
    )]
    private ?string $etat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCentre(): ?int
    {
        return $this->id_centre;
    }

    public function setIdCentre(int $id_centre): static
    {
        $this->id_centre = $id_centre;
        return $this;
    }

    public function getIdEmploye(): ?int
    {
        return $this->id_employe;
    }

    public function setIdEmploye(int $id_employe): static
    {
        $this->id_employe = $id_employe;
        return $this;
    }

    public function getAltitude(): ?float
    {
        return $this->altitude;
    }

    public function setAltitude(float $altitude): static
    {
        $this->altitude = $altitude;
        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;
        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;
        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;
        return $this;
    }
}

src/Form/ContratType.php
<?php

namespace App\Form;

use App\Entity\Contrat;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Centre;

class ContratType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('centre', EntityType::class, [
            'class' => Centre::class,
            'choice_label' => 'nom', // Affiche le nom du centre dans le formulaire
        ])
        ->add('employe', EntityType::class, [
            'class' => User::class,
            'choice_label' => 'first_name', // Affiche le nom du centre dans le formulaire
        ])
            
            ->add('date_debut', null, [
                'widget' => 'single_text'
            ])
            ->add('date_fin', null, [
                'widget' => 'single_text'
            ])
            ->add('signaturePath')
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contrat::class,
        ]);
    }
}

src/Controller/Back/ContratController.php
<?php

namespace App\Controller\Back;

use App\Entity\Contrat;
use App\Form\ContratType;
use App\Repository\ContratRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/contrat')]
final class ContratController extends AbstractController{
    #[Route(name: 'app_contrat_index', methods: ['GET'])]
    public function index(ContratRepository $contratRepository): Response
    {
        return $this->render('back/contrat/index.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_contrat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contrat);
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/contrat/new.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_show', methods: ['GET'])]
    public function show(Contrat $contrat): Response
    {
        return $this->render('back/contrat/show.html.twig', [
            'contrat' => $contrat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_contrat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/contrat/edit.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_delete', methods: ['POST'])]
    public function delete(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contrat->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($contrat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/ContratController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Form\ContratType;
use App\Repository\ContratRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/contrat')]
final class ContratController extends AbstractController{
    #[Route(name: 'app_contrat_index', methods: ['GET'])]
    public function index(ContratRepository $contratRepository): Response
    {
        return $this->render('back/contrat/index.html.twig', [
            'contrats' => $contratRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_contrat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contrat = new Contrat();
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contrat);
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/contrat/new.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_show', methods: ['GET'])]
    public function show(Contrat $contrat): Response
    {
        return $this->render('back/contrat/show.html.twig', [
            'contrat' => $contrat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_contrat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratType::class, $contrat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/contrat/edit.html.twig', [
            'contrat' => $contrat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_delete', methods: ['POST'])]
    public function delete(Request $request, Contrat $contrat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contrat->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($contrat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_contrat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contrat/edit.html.twig
<!DOCTYPE html>

<title>Edit Contrat</title>

{% block body %}
    <h1>Edit Contrat</h1>

    {{ include('contrat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contrat_index') }}">back to list</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}

templates/contrat/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Liste des Contrats{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Liste des Contrats</h1>

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ path('app_contrat_new') }}" class="btn btn-primary">
            <i class="bi bi-plus-lg"></i> Créer un Nouveau Contrat
        </a>
    </div>

    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Id</th>
                <th>Id Centre</th>
                <th>Id Employé</th>
                <th>Date Début</th>
                <th>Date Fin</th>
                <th>Signature</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrat in contrats %}
            <tr>
                <td>{{ contrat.id }}</td>
                <td>{{ contrat.centre.id }}</td>
                <td>{{ contrat.idEmploye }}</td>
                <td>{{ contrat.dateDebut ? contrat.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ contrat.signaturePath }}</td>
                <td>
                    <a href="{{ path('app_contrat_show', {'id': contrat.id}) }}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i> Voir
                    </a>
                    <a href="{{ path('app_contrat_edit', {'id': contrat.id}) }}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i> Modifier
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7" class="text-center">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/contrat/new.html.twig
<!DOCTYPE html>

<title>New Contrat</title>

{% block body %}
    <h1>Create new Contrat</h1>

    {{ include('contrat/_form.html.twig') }}

    <a href="{{ path('app_contrat_index') }}">back to list</a>
{% endblock %}

templates/contrat/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Détails du Centre{% endblock %}

{% block content %}
    <h1>Contrat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contrat.id }}</td>
            </tr>
            <tr>
                <th>Id_centre</th>
                <td>{{ contrat.idCentre }}</td>
            </tr>
            <tr>
                <th>Id_employe</th>
                <td>{{ contrat.idEmploye }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ contrat.dateDebut ? contrat.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ contrat.dateFin ? contrat.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>SignaturePath</th>
                <td>{{ contrat.signaturePath }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contrat_index') }}" class="btn btn-secondary">back to list</a>

    <a href="{{ path('app_contrat_edit', {'id': contrat.id}) }}"class="btn btn-primary">edit</a>

    {{ include('contrat/_delete_form.html.twig') }}
{% endblock %}